//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mahjong4j.resource.language.JPN {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mahjong4j.resource.language.JPN.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地和 的本地化字符串。
        /// </summary>
        internal static string CHIHO {
            get {
                return ResourceManager.GetString("CHIHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清老頭 的本地化字符串。
        /// </summary>
        internal static string CHINROTO {
            get {
                return ResourceManager.GetString("CHINROTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 九蓮宝燈 的本地化字符串。
        /// </summary>
        internal static string CHURENPOHTO {
            get {
                return ResourceManager.GetString("CHURENPOHTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大三元 的本地化字符串。
        /// </summary>
        internal static string DAISANGEN {
            get {
                return ResourceManager.GetString("DAISANGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大四喜 的本地化字符串。
        /// </summary>
        internal static string DAISUSHI {
            get {
                return ResourceManager.GetString("DAISUSHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国士無双 的本地化字符串。
        /// </summary>
        internal static string KOKUSHIMUSO {
            get {
                return ResourceManager.GetString("KOKUSHIMUSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人和 的本地化字符串。
        /// </summary>
        internal static string RENHO {
            get {
                return ResourceManager.GetString("RENHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 緑一色 的本地化字符串。
        /// </summary>
        internal static string RYUISO {
            get {
                return ResourceManager.GetString("RYUISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小四喜 的本地化字符串。
        /// </summary>
        internal static string SHOSUSHI {
            get {
                return ResourceManager.GetString("SHOSUSHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四暗刻 的本地化字符串。
        /// </summary>
        internal static string SUANKO {
            get {
                return ResourceManager.GetString("SUANKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四槓子 的本地化字符串。
        /// </summary>
        internal static string SUKANTSU {
            get {
                return ResourceManager.GetString("SUKANTSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天和 的本地化字符串。
        /// </summary>
        internal static string TENHO {
            get {
                return ResourceManager.GetString("TENHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字一色 的本地化字符串。
        /// </summary>
        internal static string TSUISO {
            get {
                return ResourceManager.GetString("TSUISO", resourceCulture);
            }
        }
    }
}
